#12: Add CRUD Operations for project
SakshiShreya/gantt-be pull request #13
Opened 2022-10-27 17:35 UTC by SakshiShreya

2022-11-04 14:59 UTC, krishna1212031 requested changes

2022-11-04 14:59 UTC, krishna1212031 commented on src/schema/project/project.js
> +    },
Instead of duration, we need to store the end date

2022-11-04 14:59 UTC, krishna1212031 commented on src/schema/project/project.js
> +    status: {
if the project status is not changed on the date of start date. the system will consider it as delayed while making the query. 
start and end date are two types. 
1. scheduled (while creating the project)
2. actual (when the project starts)

2022-11-04 14:59 UTC, krishna1212031 commented on src/models/projectModel.js
> +  },
as discussed do needful for status.

2022-11-04 19:11 UTC, SakshiShreya commented on src/schema/project/project.js
> +    },
@krishna1212031 Removed duration. End date we discussed will be calculated depending on project. So, I am not adding it right now.

2022-11-04 19:19 UTC, SakshiShreya commented on src/models/projectModel.js
> +  },
@krishna1212031 changed status messages as discussed. I will do the calculation of status while making the GET api.

2022-11-04 19:34 UTC, SakshiShreya commented on src/schema/project/project.js
> +    status: {
@krishna1212031 Added the new type of dates as discuessed

2022-11-04 19:34 UTC, SakshiShreya commented
@krishna1212031 Can you please review this code again.

2022-11-04 19:58 UTC, krishna1212031 approved these changes

2022-11-08 14:49 UTC, merged

2022-11-08 15:37 UTC, SakshiShreya commented
![](https://github.trello.services/images/mini-trello-icon.png) [BE- Project apis](https://trello.com/c/LdP64kuo/9-be-project-apis)